### ISSUE TITLE
Add a method to generate CachedCellImg< LabelMultisetType, ? > from n5 reader and dataset

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/imglib2-label-multisets#6]
Currently, there is no convenience method to open a `LabelMultisetType` dataset as a `CachedCellImg< LabelMultisetType, ? >`.
I suggest we introduce a `LabelMultisets` helper class that provides this method (and potentially more in the future). For reference, have a look at https://github.com/saalfeldlab/paintera/blob/fad335219e3c0c9089d69d0c467e578d34ecd8cb/src/main/java/org/janelia/saalfeldlab/paintera/N5Helpers.java#L669-L697:
```java
		final N5CacheLoader loader = new N5CacheLoader( reader, dataset );
		final SoftRefLoaderCache< Long, Cell< VolatileLabelMultisetArray > > cache = new SoftRefLoaderCache<>();
		final LoaderCacheAsCacheAdapter< Long, Cell< VolatileLabelMultisetArray > > wrappedCache = new LoaderCacheAsCacheAdapter<>( cache, loader );
		final CachedCellImg< LabelMultisetType, VolatileLabelMultisetArray > cachedImg = new CachedCellImg<>(
				new CellGrid( attrs.getDimensions(), attrs.getBlockSize() ),
				new Fraction(),
				wrappedCache,
				new VolatileLabelMultisetArray( 0, true, new long[] { Label.INVALID } ) );
		cachedImg.setLinkedType( new LabelMultisetType( cachedImg ) );
```
We should have both a [`LabelMultisets.open`](https://github.com/saalfeldlab/n5-imglib2/blob/e5f96f389d7c87e481d0e97ddc21e157c784526b/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java#L367) and a [`LabelMultisets.openVolatile`](https://github.com/saalfeldlab/n5-imglib2/blob/e5f96f389d7c87e481d0e97ddc21e157c784526b/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java#L383) method as in n5-imglib2's `N5Utils`.

cc @axtimwalde

**Comment by igorpisarev** [comment]
It seems to be already available here: https://github.com/saalfeldlab/n5-label-multisets/blob/master/src/main/java/net/imglib2/type/label/LabelUtils.java#L161-L167

**Comment by hanslovsky** [comment]
Unfortunately, we will need more than that, as we cannot just user `VolatileViews.wrapAsVolatile`, even when opening via `openVolatile`.

We could adopt the way it's done in [Paintera](https://github.com/saalfeldlab/paintera/blob/3dd8d589816ae2bcb9efff8aa5683a2c637febb6/src/main/java/org/janelia/saalfeldlab/util/n5/N5Data.java#L489-L507) but maybe that (the code wraps as volatile and is independent of multiset types) could even go into imglib2, but that would require some careful considerations first

**Comment by axtimwalde** [comment]
True.  I think it would be better to break API in n5-imglib2 and make `open` always use `VolatileAccess`, and make `openAsVolatile` return the `VolatileType` version, i.e. for primitive types using `wrapAsVolatile`, and for `LabelMultisetType` use the method from Paintera.  That way, `N5Utils` would support both primitive types and `LabelMultisetType` the same way, even if the path towards that goal is different.  If unification of that path seems appropriate it can happen behind that surface.

**Comment by hanslovsky** [comment]
This is available in https://github.com/saalfeldlab/n5-imglib2/pull/10
